### ISSUE TITLE
are you considering a source release?

### ISSUE THREAD

**Issue by gemvfx** [jonnysp/LDD2C4D#1]
For a 1.0 version it works pretty flawless and there is quite some potential for further improvements.
- Support for different material templates (like draft or production quality, VRay, Octane, etc.)
- Support for optimized or high-res meshes
- Adding constraints for animation.
- Adding logo to studs

**Comment by jonnysp** [comment]
the src is for now, nonpublic ! 

**Not planned yet**
- Support for different material templates (like draft or production quality, VRay, Octane, etc.)
- Support for optimized or high-res meshes
- Adding constraints for animation.
- Adding logo to studs

**Comment by gemvfx** [comment]
fine, then happy coding.
