### ISSUE TITLE
Axis center is not properly set

### ISSUE THREAD

**Issue by gemvfx** [jonnysp/LDD2C4D#2]
All objects have the same axis root position at 0,0,0 in world space.

**Comment by jonnysp** [comment]
hab gesehen du kommst aus Deutschland! kannst also in deutsch schreiben.

habe einen Source Branch gemacht! kannst dir die Quelle anschauen! Ist mein erstes Python Prog.

**Comment by gemvfx** [comment]
Gerne, hab eben erst meinen Standort eingefügt ;)
Vielen Dank! 
Für ein erstes Python Prog find ich das ziemlich beeindruckend.... und dann noch für C4D, Respekt! 
(Sollte mein LDDImport auch werden, aber leider habe ich keine Zeit gefunden weiterzumachen und bin am LIFReader gescheitert).
Auf Deinem Plug-In könnte man super aufbauen.

**Comment by jonnysp** [comment]
danke.

ich bastele schon länger an einem Konverter von LDD in OBJ (ist auch fertig) in VB.NET. Mehrere Versionen mit und ohne Preview in OpenGL ... wollte ich auch schon veröffentlichen ... das fanden die im eurobricks forum nicht so Toll und haben den Thread gleich geschlossen. da das die Firma L### nicht gerne sieht wegen datenschutz copyright ...

also ist das etwas heiß mit solchen Plugins daher wollte ich erst mal warten mit der Quelle!

**Comment by gemvfx** [comment]
Ich kenne das Thema... der LIFExtractor wurde länger heiß auf rockraidersunited.com diskutiert und war dann eine ganze Weile verschwunden. 
Mir gehts in erster Linie gar nicht so um die Geometrie, auch wenn das erst mal recht praktisch ist. 
Darats z.B. hat in eurobricks recht viele high-res bricks geposted, die man an Stelle der LDD-Version nehmen könnte. 
LDD ist leider - wie auch LDraw und Mecabricks - sehr auf sparsame Geometrie ausgerichtet und ohne sauber gebevelte Kanten sehen die Renderings immer ziemlich CGI aus... (außer man redert mit Blender, VRay oder Modo...)

In jedem Fall erst mal vielen Dank, auch für den Vertrauensvorschuss. 
Ich würde mal schauen, ob ich ein paar meiner Ideen einbauen kann. 
Leider ist meine Erfahrung mit git bzw GitHub noch recht überschaubar... 
Wäre es empfehlenswert für meine Versuche einfach einen fork zu machen?

**Comment by jonnysp** [comment]
wenn du zeit und lust hast gerne! bin auch für verbesserungen gerne offen! wie gesagt bin hobbybastler und in python gibts bestimmt noch paar kniffe die ich nach 2 Wochen nicht kennen kann.

wenn du fragen hast einfach stellen!

**Comment by jonnysp** [comment]
fixed in https://github.com/jonnysp/LDD2C4D/commit/9a410786bb67d6f5f2f8209303309b6cf7220b72

**Comment by gemvfx** [comment]
etwas besser, aber noch nicht ganz perfekt... jeder brick hat ja seinen eigenen ursprung. 
wenn man den verwendet und den brick dann nur noch durch position und rotation an die rechte stelle bringt, könnte man leichter render-instanzen verwenden. 
gerade bei extrem großen modellen sollte das gut speicher sparen... 
leider steig ich bei den matrix-berechnungen insb. bei der spiegelung noch nicht ganz durch....

**Comment by jonnysp** [comment]
schreib mir mal new email , will nicht alles in die fehler schreiben- jonnysp@gmx.de

**Comment by jonnysp** [comment]
schreib mir mal eine email jonnysp@gmx.de
