### ISSUE TITLE
it can't work~

### ISSUE THREAD

**Issue by XSpark91** [jonnysp/LDD2C4D#4]
although i fill in all the item , the buttom, 'load modle', still disable~please help me.
<img width="400" alt="wx20180803-230022 2x" src="https://user-images.githubusercontent.com/41989335/43649946-0f5bde00-9771-11e8-8c2a-782e853b8fe6.png">

**Comment by jonnysp** [comment]
@XSpark91 
1. you must install the Lego Digital Designer https://lc-www-live-s.legocdn.com/downloads/ldd2.0/installer/SetupLDD-MAC-4_3_11.zip
2. the database is **not the model** it must link to the parts database of Lego Digital Designer 
for mac
Users/spark/Library/Application Support/LEGO Company/LEGO Digital Designer/db.lif 
or search for it.
Is this correct the load button is active and you can select your model with a dialg.
3. lock at the Plugin Console for any messages.

![grafik](https://user-images.githubusercontent.com/1651241/43651731-7a0b5b78-9743-11e8-89a0-04289f109694.png)

**Comment by XSpark91** [comment]
@jonnysp 
thank you very much！
it worked perfectly!

**Comment by marcin-chwedczuk** [comment]
I think the better idea would be to use this link: 
Mac: https://www.lego.com/assets/franchisesites/ldd/installer/SetupLDD-MAC-4_3_11.zip

source: https://www.raymondson.org/virtual-robotics-club

it looks like something that does not change that often.
