### ISSUE TITLE
Cloud you tell me how to use it

### ISSUE THREAD

**Issue by victcity** [jonnysp/LDD2C4D#5]
Cloud you tell me how to use it

**Comment by jonnysp** [comment]
Thank you for your inquiry.
for mac or windows?

I have already described it for mac. is almost equal in windows.

1. clone the repository and extract it to the plugins folder in c4d r20.
2 . download and install the LDD


https://github.com/jonnysp/LDD2C4D/issues/4#issuecomment-410291477

**Comment by victcity** [comment]
> Thank you for your inquiry.
> for mac or windows?
> 
> I have already described it for mac. is almost equal in windows.
> 
> 1. clone the repository and extract it to the plugins folder in c4d r20.
>    2 . download and install the LDD
> 
> [#4 (comment)](https://github.com/jonnysp/LDD2C4D/issues/4#issuecomment-410291477)

Thank you,I got it. I use windows.
